export type ApplicationValues = {
  firstName: string;
  lastName: string;
  emailAddress: string;
  age: string;
  phoneNumber: string;
  homeState: string;
  anticipatedStartingSemester: string;
  bachelorOfArt: string;
  bachelorOfScience: string;
  associateOfArt: string;
  certificateProgram: string;
  masterProgram: string;
  graduateCertificate: string;
  levelOfEducation: string;
  priorCollegeAttendance: string;
  financialAid: string;
  veteran: string;
  heardAboutUs: string;
  comments: string;
};
